name: Sync upstream

on:
  schedule:
    - cron:  '0 2 * * *'   # Täglich um 2 Uhr UTC
  workflow_dispatch:        # Auch manuell startbar

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream
        run: git remote add upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nresare/pam-ssh-agent.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Rebase main
        run: git rebase upstream/main

      - name: Push changes
        run: git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
